### ISSUE TITLE
The demo page shows a blank page

### ISSUE THREAD

**Issue by pascalandy** [kirbysayshi/ghembedder#7]
http://output.jsbin.com/suyela

**Comment by vonpupp** [comment]
I confirm this issue, it doesn't work

**Comment by DevinWalker** [comment]
Seems this project is abandoned 😢

**Comment by deadcatssociety** [comment]
change google code pretty url to
<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
 
and ghembedder url to 

<script src="https://cdn.jsdelivr.net/npm/ghembedder@1.0.1/dist/ghembedder.min.js" type="text/javascript"></script>

then it works

**Comment by deadcatssociety** [comment]
but line number is gone :(

**Comment by kirbysayshi** [comment]
Hey, demo should be working again. I'm actually amazed that github still supports jsonp :)

```html
<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
<script src="https://cdn.jsdelivr.net/gh/kirbysayshi/ghembedder@master/dist/ghembedder.min.js" type="text/javascript"></script>
```

this should allow everything to be working again.
